language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -e .
  - pip install -r .travis-requirements.txt
script:
  coverage run --source=gcm example/manage.py test gcm
after_success:
  coveralls



